[package]
name = "oxvpn"
version = "0.1.0"
edition = "2024"
authors = ["Giovanni Martins <giovannimartins2000@gmail.com>"]

[dependencies]
eframe = {version = "0.31.1"}
env_logger = {version = "0.10"}
